version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: ['--sql_mode=', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    restart: "always"
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./application:/var/www/laravel
    depends_on:
      - database
    command: sh -c "composer install && php artisan key:generate && php artisan migrate && php artisan db:seed && php artisan sync:nbaData && php-fpm"
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./application:/var/www/laravel
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
